# Generated by Django 4.1.3 on 2022-12-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tripInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name your trip', max_length=50)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('frm', models.TextField()),
                ('to', models.TextField()),
                ('num', models.IntegerField()),
            ],
        ),
    ]
