# Generated by Django 4.1.3 on 2022-12-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0002_triprecm_delete_tripinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprecm',
            name='descp',
        ),
        migrations.RemoveField(
            model_name='triprecm',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='triprecm',
            name='month',
        ),
        migrations.RemoveField(
            model_name='triprecm',
            name='name',
        ),
        migrations.RemoveField(
            model_name='triprecm',
            name='num',
        ),
        migrations.AddField(
            model_name='triprecm',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='triprecm',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='triprecm',
            name='fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='triprecm',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
